const INGREDIENTS = Object.freeze({
    WATER: {
        ROOM_TEMPERATURE: 20,
        THRESHOLD_ALERT_QUANTITY: 50,
    },
    MILK: {
        ROOM_TEMPERATURE: 25,
        THRESHOLD_ALERT_QUANTITY: 50,
    },
    GINGER_SYRUP: {
        THRESHOLD_ALERT_QUANTITY: 10,
    },
    SUGAR_SYRUP: {
        THRESHOLD_ALERT_QUANTITY: 10,
    },
    GREEN_MIXTURE: {
        THRESHOLD_ALERT_QUANTITY: 5,
    },
    TEA_LEAVES_SYRUP: {
        THRESHOLD_ALERT_QUANTITY: 5,
    },
})

module.exports = {INGREDIENTS};